### ISSUE TITLE
autogg

### ISSUE THREAD

**Issue by ghost** [SteveKunG/Indicatia#10]
but im on 1.12.2 and it still doesnt work, i was on 1.12.2 the whole time, forgot to mention;;

**Comment by BluCobalt** [comment]
for autogg to work i'm pretty sure you have to enable it in forge mod config

**Comment by ghost** [comment]
how to do that

**Comment by ghost** [comment]
;w; how to do it?

**Comment by ghost** [comment]
How to enable it in forge mod config

**Comment by SteveKunG** [comment]
autogg has been removed.
