### ISSUE TITLE
Indicatia Mod Crashes

### ISSUE THREAD

**Issue by ItsMeBuilders** [SteveKunG/Indicatia#11]
Every time I press F4, Minecraft crashes

**Comment by MJRLegends** [comment]
You need to include more details than that buddy like mod version, crash log.

Your one line doesnt help a mod developer look and fix your issue

**Comment by SteveKunG** [comment]
Thanks, as he said you should provide a crash log not just say "it crashes".

**Comment by ItsMeBuilders** [comment]
[crash-2020-04-24_12.06.26-client.txt](https://github.com/SteveKunG/Indicatia/files/4531124/crash-2020-04-24_12.06.26-client.txt)
[crash-2020-04-24_12.12.13-client.txt](https://github.com/SteveKunG/Indicatia/files/4531125/crash-2020-04-24_12.12.13-client.txt)
[crash-2020-04-24_12.09.32-client.txt](https://github.com/SteveKunG/Indicatia/files/4531126/crash-2020-04-24_12.09.32-client.txt)
When I press F4 in a singleplayer world, I get a Minecraft loading screen that says Saving World... Then Minecraft closes.

**Comment by ItsMeBuilders** [comment]
I just downloaded the mod today so it is the latest version.

**Comment by SteveKunG** [comment]
File names doesn't look similar to my curseforge. So download here and DO NOT DOWNLOAD IT FROM 9MINECRAFT OR SHITTY WEB.

https://www.curseforge.com/minecraft/mc-mods/indicatia

**Comment by sawyer-miyake** [comment]
The same thing is happening to me, but I used all of the correct links.

**Comment by ShadowSocratex** [comment]
When opening the menu:
[crash-2020-05-13_02.30.48-client.txt](https://github.com/SteveKunG/Indicatia/files/4619147/crash-2020-05-13_02.30.48-client.txt)
java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.AbstractGui.drawCenteredString(SourceFile:104) ~[?:?]

Besides:
![image](https://user-images.githubusercontent.com/31774220/81758544-6ce90c00-94c2-11ea-919c-ed00ac45a940.png)

**Comment by PepeePL** [comment]
> File names doesn't look similar to my curseforge. So download here and DO NOT DOWNLOAD IT FROM 9MINECRAFT OR SHITTY WEB.
> 
> https://www.curseforge.com/minecraft/mc-mods/indicatia

I have this same problem. I am downloaded all from curseforge and after pressing f4 game crashes
[crash-2020-05-13_14.35.18-client.txt](https://github.com/SteveKunG/Indicatia/files/4622004/crash-2020-05-13_14.35.18-client.txt)

**Comment by SteveKunG** [comment]
@PepeePL @ShadowSocratex @0sawyer10s Make sure you have MixinBoostrap installed (For 1.14/1.15).
