### ISSUE TITLE
Cannot get Indicatia to load at all, game crashes.

### ISSUE THREAD

**Issue by TomLewis** [SteveKunG/Indicatia#2]
Im using 1.12.2 with Forge 1.12.2 - 14.23.5.2768, Ive tried the latest version with SteveKunG's-Lib-1.12.2-1.1.3.jar and without, the closest I have got is using Indicatia-1.12.2-1.2.5.jar without the Lib, this loads MC but tells me I need the Lib, but with the lib it crashes again.

**Comment by SteveKunG** [comment]
But the crash log?

**Comment by TomLewis** [comment]
If im using 1.12.2 with Forge 1.12.2 - 14.23.5.2768, tell me the versions I should be using and if I need the Lib, and what version of the lib, and then tell me what file the crash log is in.

**Comment by SteveKunG** [comment]
1. https://www.google.com/search?q=minecraft+crash+log+location&oq=minecraft+crash+log+location&aqs=chrome..69i57.4087j0j0&sourceid=chrome&ie=UTF-8
2. Forge latest + Lib latest

**Comment by MCPETH** [comment]
5555+

**Comment by danieldev-gh** [comment]
i have the same problem 
here is the log
[crash-2019-08-20_09.46.58-client.txt](https://github.com/SteveKunG/Indicatia/files/3519093/crash-2019-08-20_09.46.58-client.txt)

**Comment by SteveKunG** [comment]
@EySwag You are downloaded from another website and seems it’s old version (1.2.1)
Only curseforge website is supported.
