### ISSUE TITLE
Default potion icon blocks the modded hud

### ISSUE THREAD

**Issue by Feathertoes** [SteveKunG/Indicatia#20]
in the top right corner, you cannot view any information because of the default potion icon

my idea for a fix for this might be to add an option to remove the vanilla potion HUD in favour of the modded one, or just make the potion icon less opaque when using the mod

![2020-11-15_11 12 40](https://user-images.githubusercontent.com/70271757/99190291-b9442b80-2733-11eb-9ca3-bb5926587bce.png)

**Comment by SteveKunG** [comment]
You can disable Vanilla Potion HUD by editing config.
.minecraft/config/indicatia-client.toml > change enableVanillaPotionHUD to false.
