### ISSUE TITLE
Keystrokes and Capes

### ISSUE THREAD

**Issue by Errorcrafter** [SteveKunG/Indicatia#21]
Hi @SteveKunG ,

I downloaded the 1.16.3 version of your mod but have found out that the keystrokes module and custom capes shown on your CurseForge page do not appear. Is this a bug or an intentional omission? Thank you

**Comment by SJKZ1-2565** [comment]
> Hi @SteveKunG ,
> 
> I downloaded the 1.16.3 version of your mod but have found out that the keystrokes module and custom capes shown on your CurseForge page do not appear. Is this a bug or an intentional omission? Thank youf
Uhhhh i think Custom capes and Keystroke is removed

**Comment by SJKZ1-2565** [comment]
> Hi @SteveKunG ,
> 
> I downloaded the 1.16.3 version of your mod but have found out that the keystrokes module and custom capes shown on your CurseForge page do not appear. Is this a bug or an intentional omission? Thank you

Custom cape and Keystroke is removed
