### ISSUE TITLE
Game crashes when trying to load

### ISSUE THREAD

**Issue by TTLES33** [SteveKunG/Indicatia#23]
Hello,

i!m trying to load minecraft 1.16.3 with forge and Indicatia.
Byt when i trying to start game, thist error shows:

![image](https://user-images.githubusercontent.com/73744077/103896551-729afe00-50f2-11eb-954f-43f1139a3d7e.png)

And here is my crash log:
[crash-2021-01-07_13.58.02-client.txt](https://github.com/SteveKunG/Indicatia/files/5781748/crash-2021-01-07_13.58.02-client.txt)

**Comment by SteveKunG** [comment]
Latest Indicatia doesn't support 1.16.3, Please switch to use 1.16.4 instead.

**Comment by TTLES33** [comment]
I'm not using latest version. I'm using 1.16.3 [verison](https://www.curseforge.com/minecraft/mc-mods/indicatia/files/3088507)

**Comment by SteveKunG** [comment]
Yeah, just update it.

**Comment by TTLES33** [comment]
So there is no way to use 1.16.3? I want use it for same servers.

**Comment by SteveKunG** [comment]
Sadly, it is unsupported. 1.16.4 and forge is stable than 1.16.3.
