### ISSUE TITLE
Crash when clicking on the "Preview" button in the Offset settings gui (FABRIC)

### ISSUE THREAD

**Issue by moehreag** [SteveKunG/Indicatia#33]
### What happened:
The game crashes with the description "_Unexpected Error, the call method_3228 is not cancellable_" and the exit code _255_.

Game Version: 1.16.5//fabric loader 0.11.6
Mods used: 

- Indicatia 4.1.5-fabric
- SteveKunG's lib 4.1.3-fabric
- architectury-fabric 1.17.23
- cloth-config 4.11.26-fabric
- fabric-api 0.34.6+1.16

I included the crash report here: [crash-2021-06-28_15.08.19-client.txt](https://github.com/SteveKunG/Indicatia/files/6726496/crash-2021-06-28_15.08.19-client.txt)

I'd be nice if a fix maybe could be in an updated version for 1.17? If there are no capacities for solving this problem, it doesn't matter too much.

What I would also love to see in this mod are more even HUD options, like CPS and Keystrokes (added back in) as well as maybe a nicer option to move things around (like KronHUD? (I am not sure if it's still maintained))

**Comment by SteveKunG** [comment]
1.17 will getting ported soon, I'm waiting for forge 1.17 (probably 1.17.1 instead).
Also there is no other mods like keystroke thing on modern versions?

**Comment by moehreag** [comment]
No, as far as I know, there only is one keystroke/ CPSHud mod for 1.16.x/fabric ( which is Kronhud) and not a single one for 1.17/fabric. I already asked Lambdaurora in their Discord server if they're willing to update their keystrokes mod, but replied instead that "_a lot of its code is worth trash_". I'm too bad at Java to port it (or Kronhud) to a new version, unfortunately.
