### ISSUE TITLE
Issues with Potion HUD offset/positioning

### ISSUE THREAD

**Issue by InsidiousPilot** [SteveKunG/Indicatia#34]
The Potion HUD's effect names and subordinate time durations in v4.1.6 are misaligned in both the "right" and "hotbar left" positions. The images below show this.
![2021-07-04_14 54 56](https://user-images.githubusercontent.com/86931474/124399333-e6037e00-dcd7-11eb-9c50-f993743c330f.png)
![2021-07-04_14 54 27](https://user-images.githubusercontent.com/86931474/124399334-e69c1480-dcd7-11eb-9a2f-9c640be9491a.png)
![2021-07-04_14 54 39](https://user-images.githubusercontent.com/86931474/124399335-e69c1480-dcd7-11eb-992c-664963a4f132.png)
![2021-07-04_14 54 48](https://user-images.githubusercontent.com/86931474/124399336-e69c1480-dcd7-11eb-96b5-dab506a0578b.png)

Likewise, in the aforementioned screenshots, the display cap is set to 5 though 6 effects total are rendered on the Potion Hud.

Another issue which may be more difficult to tackle is the ping display of other players on servers, Hypixel in particular. They have gone through a recent server hosting makeover, so this may be the issue, but other player's connections are shown as 1/0.00s. This can be seen in the screenshot below.
![2021-07-04_15 23 05](https://user-images.githubusercontent.com/86931474/124399885-c2dacd80-dcdb-11eb-9ba6-bca50a7d3b0a.png)

These next items are not so much bugs but a possible improvements:
Depending on the active number of effects displayed on the Potion HUD, the HUD should automatically shift the position of the whole Potion HUD downward on the Y axis when more effects are added to center the effects list as more are added. There's an example of what this may look like:
![ex](https://user-images.githubusercontent.com/86931474/124399938-25cc6480-dcdc-11eb-9e99-154db76936d8.png)
Lastly, The pre-1.7 armor damage appears to be slightly discolored. The overlaid hue appears magenta as opposed to red. Its a very minor thing, but is none the less something that I've noticed.

I hope this post was helpful to you and I'd like to see more updates in the future!

**Comment by SteveKunG** [comment]
Thanks for helping me fixing bugs!

Hypixel Ping is always 1 on their server which I can't fix it and I don't know why. Probably performance issue.

Potion HUD code is kinda spaghetti for now, I can only sorted them with max duration first.
And I added new option to display duration on vanilla Potion HUD.

![image](https://user-images.githubusercontent.com/6128413/128598910-0c82613e-eba2-47d6-8f0a-e8a4922853df.png)

Also 1.7 armor seems fine to me, I just put vanilla hurt overlay on armor layer so it might not similar to 1.7.

**Comment by moehreag** [comment]
The Ping "issue" may be caused by the fact the Hypixel (and other Servers) are using Proxy-Networks to redirect players. This causes the Backend server to think all players have a 1ms Ping (because the server only sees the connection from the proxy and thus doesn't know better). I also think that this can't be fixed at client-side.
