### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by ghost** [SteveKunG/Indicatia#38]
I can not start the game with this mod and libraries for it.
![image](https://user-images.githubusercontent.com/94476270/142034532-84c5ce51-2c20-46b9-9c6e-ec4434d9068a.png)
[crash-2021-11-16_20.19.31-client.txt](https://github.com/SteveKunG/Indicatia/files/7548502/crash-2021-11-16_20.19.31-client.txt)

**Comment by ghost** [comment]
I found the problem: conflicts with Optiforge. Pls, fix

**Comment by SteveKunG** [comment]
I'd say no, Because optifine cause a lot of issues for many mods.
