### ISSUE TITLE
Incompatibility with Optifine/Optifabric on 1.18

### ISSUE THREAD

**Issue by gxjakkap** [SteveKunG/Indicatia#39]
I'm Running this combination of mods and encountered a crash.
![image](https://user-images.githubusercontent.com/55027998/144347673-dd7601c1-0b70-419a-98e9-f59c7aaa1d72.png)

Here's [crash log](https://ghostbin.com/UfqEC/raw)

Tried removing Optifine/Optifabric and it works fine. Running Optifine/Optifabric with only Architectury also works fine.

Not sure if this issue is related to or similar to [this](https://github.com/architectury/architectury-api/issues/3) issue on Architectury or not.

**Comment by ghost** [comment]
Same issue! Works totally fine without OptiFabric, but when I put it back into the mods folder it just doesn't launch at all
