### ISSUE TITLE
Indicatia incompatible with Ring of Fairies from Trinkets and Baubles

### ISSUE THREAD

**Issue by Geezt435** [SteveKunG/Indicatia#4]
![2020-03-31_13 43 58](https://user-images.githubusercontent.com/46617557/78113144-de4c8e00-7431-11ea-9778-bd9eadb9b84e.png)

Player's eye of sight is not changed when player's wearing Ring of Fairies

**Comment by SteveKunG** [comment]
Which version? 1.12.2?

**Comment by Geezt435** [comment]
Yes 1.12.2

**Comment by Geezt435** [comment]
> Which version? 1.12.2?

Yes 1.12.2

**Comment by SteveKunG** [comment]
Did you try turned off Smooth Sneaking View option?

**Comment by Geezt435** [comment]
Haven't tried that
