### ISSUE TITLE
[1.16.5]Failure to load game with journey map 5.8.0 beta 3 and Indicatia v4.1.8-forge (and dependencies)

### ISSUE THREAD

**Issue by PokeMaserJ** [SteveKunG/Indicatia#41]
Installing both of these mods makes the game fail to load. No Crash report oddly, but I do have a log https://gist.github.com/PokeMaserJ/68e89b156c38691a23a11d4ad56e2789

**Comment by mysticdrew** [comment]
This is an error do to a mixin added by Indicatia and a coremod added by journeymap. 
I should be able to resolve this on my end.

**Comment by mysticdrew** [comment]
I have this fixed on my end for the next release, (beta 4) keep an eye on the issue in the journeymap github, I will close it there when I publish beta 4. You an probably close this issue here.

**Comment by mysticdrew** [comment]
Fixed in journeymap 5.8.0 beta4, should be on curseforge shortly.
