### ISSUE TITLE
Instant Crash with Optifine

### ISSUE THREAD

**Issue by zachsai** [SteveKunG/Indicatia#45]
https://pastebin.com/vDW9P0TB

![image](https://user-images.githubusercontent.com/63996164/159347302-714e6585-e57c-45be-9ce6-03ea43f0665d.png)

![image](https://user-images.githubusercontent.com/63996164/159347316-a46f5a63-0a6c-4c79-a978-9697ae21d254.png)

**Comment by SteveKunG** [comment]
Optifine is unsupported. Not worth to maintain with.

**Comment by zachsai** [comment]
lol no downloads then, optifine is a must and other gui mods have worked around it. Thats too bad
