### ISSUE TITLE
Indicatia Config

### ISSUE THREAD

**Issue by ghost** [SteveKunG/Indicatia#47]
Hello, I've been using Indicatia for 1.18.1, wanting to use it for 1.18.2, but the servers that I was playing only suppported 1.18.1, so I did that, then I played with it and it is very good, however, one of the servers, updated to 1.18.2, forcing me to make a copy of all the mods, but updated to 1.18.2, Indicatia however crashed when launching minecraft, and so I put Cloth Config 6.2.57 for 1.18.2, and it worked except the HUD. I thought because 1.18.1 and 1.18.2 are versions right next to each other they should have the same config and same keys, if not I would change some to be like 1.18.1 and backed it up, but I didn't see the HUD on my screen and long story short I read on curseforge the line "Rewrite and big clean up entire mod" which leads me to think that you've basically deleted the entire core of Indicatia, but at the same time wouldn't make sense, so how do you activate the config menu on Indicatia on 1.18.2? In mod menu only 5 configurations are shown.

**Comment by SteveKunG** [comment]
Yes, all of that features have been removed. I recommended to use others HUD mods which has better customization. And all the features left in the Indicatia are only 5 main features.
