### ISSUE TITLE
HUD glitch

### ISSUE THREAD

**Issue by 0Atrox0** [SteveKunG/Indicatia#7]
Everytime im in a game, Indicatia always does this
![Capture](https://user-images.githubusercontent.com/63568372/79084833-e090d100-7cea-11ea-81d2-a05cd65c0bc4.PNG)

What do I do?'

I have already reinstalled 3 times, I have restarted MC and my PC

Im also on version 1.15.2

**Comment by SteveKunG** [comment]
Install MixinBoostrap

**Comment by 0Atrox0** [comment]
MixinBoostrap is installed

**Comment by SteveKunG** [comment]
Any other mods installed? It should be work fine if MixinBoostrap has installed.

**Comment by 0Atrox0** [comment]
I reinstalled MixinBootstrap and then I launched the game and now it keeps crashing.

**Comment by SteveKunG** [comment]
Crash report?

**Comment by SteveKunG** [comment]
![2020-04-16_10 28 40](https://user-images.githubusercontent.com/6128413/79411533-4328ec00-7fcd-11ea-8247-6a4ced917c7f.png)

My test seems work fine. Can you provide your current mod list?
